"""create signals tables

Revision ID: 1639ba3431dd
Revises: c7846bb44ead
Create Date: 2026-08-02 20:51:30.236835

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1639ba3431dd"
down_revision: str | Sequence[str] | None = "c7846bb44ead"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signals",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum(
                "M1", "M5", "M15", "M30", "H1", "H4", "D1", "W1", "MN", name="candle_timeframe"
            ),
            nullable=False,
        ),
        sa.Column("signal_type", sa.Enum("BUY", "SELL", name="signal_type"), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("take_profit", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("risk_reward", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "TRIGGERED",
                "EXPIRED",
                "CANCELLED",
                "CLOSED",
                "SUCCESSFUL",
                "STOPPED_OUT",
                name="signal_status",
            ),
            nullable=False,
        ),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("profit_loss", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["ai_analysis.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signals_analysis_id"), "signals", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_signals_asset_id"), "signals", ["asset_id"], unique=False)
    op.create_table(
        "signal_bookmarks",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "signal_id", name="uq_signal_bookmarks_user_signal"),
    )
    op.create_index(
        op.f("ix_signal_bookmarks_signal_id"), "signal_bookmarks", ["signal_id"], unique=False
    )
    op.create_index(
        op.f("ix_signal_bookmarks_user_id"), "signal_bookmarks", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signal_bookmarks_user_id"), table_name="signal_bookmarks")
    op.drop_index(op.f("ix_signal_bookmarks_signal_id"), table_name="signal_bookmarks")
    op.drop_table("signal_bookmarks")
    op.drop_index(op.f("ix_signals_asset_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_analysis_id"), table_name="signals")
    op.drop_table("signals")
    # ### end Alembic commands ###
