"""create economic events table

Revision ID: 1e4e1b3c8c7c
Revises: 3636f44102c0
Create Date: 2026-08-01 14:20:09.690756

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1e4e1b3c8c7c"
down_revision: str | Sequence[str] | None = "3636f44102c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economic_events",
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("event_name", sa.String(length=255), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "INFLATION",
                "EMPLOYMENT",
                "GROWTH",
                "CENTRAL_BANK",
                "CONSUMER",
                "HOUSING",
                "OTHER",
                name="economic_event_category",
            ),
            nullable=False,
        ),
        sa.Column(
            "importance",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", name="economic_event_importance"),
            nullable=False,
        ),
        sa.Column("forecast", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("previous", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("actual", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("surprise", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column(
            "status",
            sa.Enum("SCHEDULED", "RELEASED", "REVISED", "CANCELLED", name="economic_event_status"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("release_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_economic_events_currency_release_time",
        "economic_events",
        ["currency", "release_time"],
        unique=False,
    )
    op.create_index(
        "ix_economic_events_importance_release_time",
        "economic_events",
        ["importance", "release_time"],
        unique=False,
    )
    op.create_index(
        "ix_economic_events_natural_key",
        "economic_events",
        ["country", "currency", "event_name", "release_time"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_economic_events_natural_key", table_name="economic_events")
    op.drop_index("ix_economic_events_importance_release_time", table_name="economic_events")
    op.drop_index("ix_economic_events_currency_release_time", table_name="economic_events")
    op.drop_table("economic_events")
    # ### end Alembic commands ###
