"""create news tables

Revision ID: 3636f44102c0
Revises: 6ecc6c49e631
Create Date: 2026-08-01 13:45:58.176868

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3636f44102c0"
down_revision: str | Sequence[str] | None = "6ecc6c49e631"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_sources",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=False),
        sa.Column(
            "tier", sa.Enum("TIER_1", "TIER_2", "TIER_3", name="news_source_tier"), nullable=False
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_sources_name"), "news_sources", ["name"], unique=True)
    op.create_table(
        "news_articles",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "CENTRAL_BANK",
                "INFLATION",
                "EMPLOYMENT",
                "GDP",
                "INTEREST_RATES",
                "POLITICS",
                "WAR",
                "ENERGY",
                "COMMODITIES",
                "CRYPTO",
                "REGULATION",
                "CORPORATE_EARNINGS",
                "BREAKING_NEWS",
                name="news_category",
            ),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column(
            "importance",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "IGNORE", name="news_importance"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["news_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_news_articles_source_id"), "news_articles", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_news_articles_url"), "news_articles", ["url"], unique=True)
    op.create_index(
        "ix_news_articles_category_importance",
        "news_articles",
        ["category", "importance"],
        unique=False,
    )
    op.create_table(
        "news_sentiment",
        sa.Column("article_id", sa.Uuid(), nullable=False),
        sa.Column(
            "sentiment",
            sa.Enum(
                "VERY_BULLISH",
                "BULLISH",
                "NEUTRAL",
                "BEARISH",
                "VERY_BEARISH",
                name="news_sentiment_label",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("affected_assets", sa.JSON(), nullable=False),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["news_articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_news_sentiment_article_id"), "news_sentiment", ["article_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_news_sentiment_article_id"), table_name="news_sentiment")
    op.drop_table("news_sentiment")
    op.drop_index("ix_news_articles_category_importance", table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_url"), table_name="news_articles")
    op.drop_index(op.f("ix_news_articles_source_id"), table_name="news_articles")
    op.drop_table("news_articles")
    op.drop_index(op.f("ix_news_sources_name"), table_name="news_sources")
    op.drop_table("news_sources")
    # ### end Alembic commands ###
