"""create ea_tokens

Revision ID: b3f9d27c61e5
Revises: 29015ec49225
Create Date: 2026-09-11 10:00:00.000000

ADR-161: tokens a MetaTrader 5 Expert Advisor presents to read the signal
feed. Written by hand rather than autogenerated, so none of the
`uq_telegram_accounts_*` drops described in 29015ec49225 can creep in.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b3f9d27c61e5"
down_revision: str | Sequence[str] | None = "29015ec49225"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "ea_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("hint", sa.String(length=8), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        # CASCADE: a deleted user's EAs must stop working, and a token row
        # with no owner has nothing left to authenticate as.
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ea_tokens_user_id"), "ea_tokens", ["user_id"], unique=False)
    op.create_index(op.f("ix_ea_tokens_token_hash"), "ea_tokens", ["token_hash"], unique=True)


def downgrade() -> None:
    op.drop_index(op.f("ix_ea_tokens_token_hash"), table_name="ea_tokens")
    op.drop_index(op.f("ix_ea_tokens_user_id"), table_name="ea_tokens")
    op.drop_table("ea_tokens")
